import type { Metadata } from "next";
import "./globals.css";
import { Playfair_Display, Source_Sans_3 } from "next/font/google";


const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "700"], // Specify needed weights
  variable: "--font-playfair", // Define a CSS variable for Tailwind
});

const sourceSans = Source_Sans_3({
  subsets: ["latin"],
  weight: ["400", "700"], // Add weights you need
  variable: "--font-source-sans", // Define CSS variable for Tailwind
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${playfair.variable} ${sourceSans.variable}`}>
      <body className="antialiased" style={{ backgroundColor: "#D8C3A5" }}>
        {children}
      </body>
    </html>
  );
}
